services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: groceries-analyzer
    environment:
      - OCR_ENDPOINT=${OCR_ENDPOINT}
      - OCR_KEY=${OCR_KEY}
      - AI_ENDPOINT=${AI_ENDPOINT}
      - AI_KEY=${AI_KEY}
      - AI_DEPLOYMENT=${AI_DEPLOYMENT}
      - API_KEY=${API_KEY}
      - ELASTICSEARCH_ENDPOINT=${ELASTICSEARCH_ENDPOINT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - '8089:8080'
    networks:
      - coolify

#  elasticsearch:
#    image: elasticsearch:8.15.2
#    container_name: groceries-analyzer-elastic
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=true
#      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
#    networks:
#      - app-network
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#  kibana:
#    image: kibana:8.15.2
#    container_name: groceries-analyzer-kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_ENDPOINT} # http://elasticsearch:9200
#      - ELASTICSEARCH_USERNAME=elastic  # Default user for Kibana access
#      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}  # Define a secure password
#    volumes:
#      - kibana-data:/usr/share/kibana/data
#    ports:
#      - '5601:5601'
#    depends_on:
#      - elasticsearch
#    networks:
#      - app-network
#
#volumes:
#  elasticsearch-data:
#    driver: local
#  kibana-data:
#    driver: local

networks:
  coolify:
    external: true