services:
  app:
    image: 'groceries-analyzer:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - app-network
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elasticsearch:8.15.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - '9200:9200'
    networks:
      - app-network
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.15.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  # Use HTTP to connect to Elasticsearch
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - app-network

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  app-network:
    driver: bridge
